version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  
jobs:
  example-job:
    parallelism: 15
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: large
    steps:
      - docker/build:
          dockerfile: Dockerfile 
          no_output_timeout: '1h' 
          image: jq8dh1894/docker
  example-job2:
    parallelism: 15
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: large
    steps:
      - docker/build:
          dockerfile: Dockerfile 
          no_output_timeout: '1h' 
          image: jq8dh1894/docker 

workflows:
  example-workflow:
    jobs:
      - example-job
      - example-job2
