version: 2.1

orbs:
  docker: circleci/docker@2.0.1

working_dir: &working_dir ~/app
  
jobs:
  example-job:
    parallelism: 15
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: large
    steps:
      - docker/build:
          dockerfile: /home/Dockerfile 
          no_output_timeout: '1h' 
          image: ubuntu
  example-job2:
    parallelism: 15
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: large
    steps:
      - docker/build:
          dockerfile: /home/Dockerfile 
          no_output_timeout: '1h' 
          image: ubuntu 

workflows:
  example-workflow:
    jobs:
      - example-job
      - example-job2
